### ISSUE TITLE
Issues with phpdoc_to_return_type

### ISSUE THREAD

**Issue by nicolas-grekas** [PHP-CS-Fixer/PHP-CS-Fixer#4511]
I'm playing with this rule on the Symfony codebase, here are some issues I found while doing so:

- [x] `@return false` should become `: bool` (#4580)
- [x]  `@return object[][]` should become `: array` (#4589)
- [x]  `@return string[]|int[]` should become `: array` (#4591)
- [x]  `@return \Traversable|CacheItem[]` should become `: iterable` (#4591)
- [x]  `@return iterable|VoterInterface[]` should become `: iterable` (#4591)
- [ ]  `@return $this` should become `: object` (related to #3932), unless the method is final, in which case it should be `: self` to allow using it on PHP 7.1
- [x]  `@return static` should become `: object`, unless the method is final, in which case it should be `: self` to allow using it on PHP 7.1

For the last two, we've decided it should be the rule for the Symfony codebase, so could be a separate rule maybe (forcing `: object` when a `return $this`/`return static` annotation is found and a return type is found too)

Note that I find a lot of false-positive editions related to return-type covariance: eg a child method declares `@return Foo[]`, which leads to `: array`, while the parent says `: iterable`. But I guess we're hitting the limit of the tool and that's fine, there must be some.

**Comment by SpacePossum** [comment]
checked off `static` as I think we handle is nicely now (including on [PHP8](https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/3057facfa4c5a70d2bcaec7c50069381b09de2f6) )

**Comment by Wirone** [comment]
[I looked at tests](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/tests/Fixer/FunctionNotation/PhpdocToReturnTypeFixerTest.php) and I believe the only case missing is `@return $this`. I've marked todo item about `static` as resolved.

**Comment by Wirone** [comment]
@nicolas-grekas what's the current status from the Symfony side? I believe you don't need the support for PHP 7.1 (`: object` return type). Maybe we can just close this? 🙂

**Comment by nicolas-grekas** [comment]
Correct, thanks for the reminder.
